### ISSUE TITLE
Suggestion: VAR tracking 

### ISSUE THREAD

**Issue by madquills** [inkle/inky#10]
Simply put, as with Unity, a visual VAR tracker so you can check that your VAR logic is working as intended.

**Comment by joethephish** [comment]
For implementation:

- Needs UI design
  - Do we want the ability to log the value of a variable between every choice-turn, so you can track what happened in the past? Or just a "current" view somewhere on the screen? Where is the UI to add/remove watched variables? Do you pick from a list, or type in a variable name?
- Needs features added to inklecate to allow you to list all global variables via command line tool (assuming user can pick rather than type). Tool is already able to print the value of a variable when requested.
- Will then require a code path all the way from the renderer, depending on where the view is implemented (toolbar, player view?) through liveCompiler.js, to the main process via IPC, into the inklecate.js wrapper where the request will be made, and the result sent back in reverse.

We shouldn't request the contents of all variables all the time, since they'll all have to go via the command line stdin/stdout interface.

**Comment by madquills** [comment]
• UI DESIGN 
I think the important part is the current view. That's all one would need to test the VAR logic (and any choices that should only be available as a result) is WAI. 

Sorry I can't do more to help, I'm totally unable to code etc!

**Comment by joethephish** [comment]
Here's my idea for the design. Essentially, it's possible to write a little snippet of ink that's run after every turn to give you a trace of what's happening in your story. You could also use it for other debug purposes though, by actually changing the state of the story.

Potentially we could also add a shortcut for adding variable watches like the two in this example.

It might also be helpful to be able to define a snippet of ink that happens before the story starts evaluating, if you want to jump straight to a particular section for testing.

![image](https://cloud.githubusercontent.com/assets/858967/17242703/7830c188-5570-11e6-8728-088e2d8ce87f.png)

**Comment by madquills** [comment]
Love it!

**Comment by joethephish** [comment]
Merged this feature into master. Expect it in the next inky release. (Though I haven't done the "at start" part just yet, it's less critical and I have many other things to be doing, sigh!)
