### ISSUE TITLE
More complex functions in the every-turn VAR tracker?

### ISSUE THREAD

**Issue by ladyisak** [inkle/inky#106]
Hi, I'm wondering how to use more complex ink in the VAR tracker. Essentially, what I'm trying to do is link the results of fairmath testing a friendship stat to simple keywords so I can keep an eye on how, broadly, the friendship with the NPC is going.

When I try something like this:

```
VAR friend_relationship = 1001

=== function raise(ref x) ===
    ~ x = x + 1000

=== function lower(ref x) ===
    ~ x = x + 1

=== function upness(x) ===
    ~ return x / 1000

=== function downness(x) ===
    ~ return x % 1000

=== function very_high(x) ===
    ~ return (1 * upness(x) >= downness(x) * 9)

=== function high(x) ===
    ~ return (4 * upness(x) >= downness(x) * 6)

=== function low(x) ===
    ~ return (6 * upness(x) <= downness(x) * 4)

=== function very_low(x) ===
    ~ return (9 * upness(x) <= downness(x) * 1)

=== function friend_status(x) ===
{
  - low(x):
   ~ return "BAD"
 - high(x):
  ~ return "GOOD"
}
```

And try this:

```
{friend_status(friend_relationship)}
```

Instead of "GOOD" or "BAD" I get the value of `friend_relationship`.

What's going on here? What am I missing?

**Comment by joningold** [comment]
Hey!

So if I paste your code into inky it works fine -- although i had to add a
third line to your "Good/bad" function to handle the 'middle' state.

=== function friend_status(x) ===
{
  - low(x):
   ~ return "BAD"
 - high(x):
  ~ return "GOOD"
  - else:
    ~ return "OKAY"
}


Note that functions can just print text out directly, so you can also do

=== function friend_status(x) ===
{
  - low(x):
    BAD
 - high(x):
    GOOD
  - else:
    OKAY
}


But yeah, otherwise it seems okay to me...?

cheers
jon

**Comment by isakgrozny** [comment]
The thing is that it works when I try it in the main ink file, but when I try to use it as an expression via "Add watch expression ..." in the Story menu, it returns the value of `friend_relationship`. 

For clarity, I mean when I plug it in here instead of `x is {x}`:
https://puu.sh/wW6oB/2e31288a73.png

**Comment by joethephish** [comment]
What are you inserting for your x?

**Comment by ladyisak** [comment]
Three years on — I think I did eventually figure out the issue, but I don't remember how! In any case, closing this now, as it's a bit moot.
