### ISSUE TITLE
Feature request: click a line in the player window and jump to that line in the ink

### ISSUE THREAD

**Issue by joningold** [inkle/inky#12]
I'm not sure how possible / plausible this is, but it'd be super useful for fixing typos, etc, if you could click a word in the output window and "go there" in the main ink view

**Comment by joethephish** [comment]
Pretty hard, this one, unfortunately. Would require more debug information to make it over into the final runtime text, and that doesn't currently exist.

However, let's leave the issue open, because it would indeed be awesome!

(In fact, if you could make it work, that also opens the door to making light edits *within the player view*, almost like inklewriter. But considering that almost makes my head explode.)

**Comment by joethephish** [comment]
Okay, implemented in 0.2.1! (Because this is what I do for fun at the weekend...) Give it a try (alt-click to jump to line in editor): https://github.com/inkle/inky/releases/tag/0.2.1

**Comment by joningold** [comment]
Nice!
