### ISSUE TITLE
Playback matches position in editor

### ISSUE THREAD

**Issue by nicholasderk** [inkle/inky#129]
I'm not sure if this already exists (I searched for "play" and "playback" before posting), the only thing I've found is the alt+click functionality to jump around in the editor view, but the playback view always starts at the beginning. My stories are getting large enough that working on later parts of it require playback of 20-30 minutes to get that far in the playback view. I thought breaking my files down into includes would correct this, but since the name space is dependent on the knots and not the filenames, it still is back at the beginning in the playback window regardless of what include file I'm editing.

This differs from my experience in Inklewriter where it somehow figures out the variables and path through to switch to playback view wherever you are editing.

**Comment by joethephish** [comment]
Agreed, this would be a cool feature! In inklewriter this is doing something pretty clever - it's actually pathfinding through the story to find a way to the point in the story that you're editing, which is non-trivial. Unfortunately in ink it's even harder since ink stories can structured in more complicated ways.

So, to cut a long story short, yeah, we'd like to and it would be awesome, but it's unlikely to ever be as "complete" as the inklewriter version, if we even managed at all.

In the meantime, I'd recommend just using diverts in your main ink file to decide where to start the story from.

An easier feature to add to inky would be a more "official" way of doing this in general - we could add a feature that lets you tell it a starting knot so it always start from that point without you having to edit the main ink file.

**Comment by nicholasderk** [comment]
Doesn't seem worth it if you put the divert right at the start of the main ink file, which also allows you to do it when testing in your final playback Unity or other project.

And I mean I totally would've figured out this work around on my own it's not like I needed to open an issue or anything, I really did it for you to show off...
