### ISSUE TITLE
Need to know how to export so other people can see & play?

### ISSUE THREAD

**Issue by Hoppy2003** [inkle/inky#185]
I'm trying to figure out how to make a link or something that I can give people if they want to play so it's not just in my laptop. The export to web hasn't worked and I don't know what the other export options are so I haven't tried them, and I'm new so I don't even know if this is possible. Help?

thank u 
~Hoppy

**Comment by JLevstein** [comment]
Hey @Hoppy2003,

This feels quite late after the fact, but you'll need to either host your ink file somewhere and send someone a link to the file or send it to a person directly. Inky doesn't auto-upload your ink file to a server, but it would be cool if it did!

**Comment by Hoppy2003** [comment]
Oh! thank you for answering @JLevstein I didn't think anyone would haha. I still am kinda lost though, I don't know how to host the file? I'm such a newbie :,) and I tried sending the link but that didn't work

**Comment by evangelinepapanicola** [comment]
Hey @Hoppy2003 !

So when you use the export for web option, you should get a folder that looks something like this:

![image](https://user-images.githubusercontent.com/33719860/56032063-0d498b80-5d19-11e9-908e-e86f2320ef8b.png)

(The file named "player" in my example will be called whatever the name of your project is when you export)
You need to upload these files to a server, and then you can go to the index.html file in a browser in order to play your story.

I've never used itch.io before but I believe you can host your game here for free! https://itch.io/developers

You'd just need to sign up for an account and upload the files to the relevant area.

I hope this helps 😊

**Comment by Hoppy2003** [comment]
@evangalinepapanicola i am late to respond to this, but ty! i will try this out :)

**Comment by lunarcloud** [comment]
So, found some instructions at the bottom of https://www.inklestudios.com/ink/web-tutorial/ "Upload to itch.io" That should clear things up hopefully

**Comment by lunarcloud** [comment]
This should probably be closed unless @Hoppy2003 needs more information
