### ISSUE TITLE
Glue selected option to prompt

### ISSUE THREAD

**Issue by hlship** [inkle/inky#186]
In "80 days" it's often the case that the game text prompt is followed by options that glue in after the prompt.  That is, the selected option is "spliced" into the text immediately following the prompt.  Inside Ink, or in the exported web version of the game, I don't see a way to do the same.

![image](https://user-images.githubusercontent.com/52660/54629602-28d0b780-4a35-11e9-9217-004e286d4fab.png)

**Comment by hlship** [comment]
s/resolver/revolver/

**Comment by hlship** [comment]
So I'd like to see it say "dragons, and cracked the cyanide" all together.

**Comment by bkmeneguello** [comment]
I have this very same issue. I think in 80 days they did this in second level, by concatenating the text to the previous text buffer, since there they are using Unity but would be awesome to be able to preview that in Inky.
The simple presence of glue mark should signal this behavior.

**Comment by joningold** [comment]
This is a UI issue, not an ink-level one. To explain - the ink presents text, choice, text, but it's up to the game how to display that content. If you intend the outcome of a choice to be 'glued' to the previous paragraph, you'll need to write UI code to actually do that.

You can't do this using glue because glue happens *within* the ink processing step; by the time the output appears, the glue has been resolved. 

For 80 Days, we labelled choices with a leading "..." if there were intended to be glued in this fashion; the engine then looked for the dots, stripped them out, and told the UI to append the text rather than starting a new paragraph.

This is the same approach as you might take if a line was intended to be dialogue for a certain character; or a chapter title; or an instruction to play a sound effect, etc etc.
