### ISSUE TITLE
Error when 'npm start' on linux

### ISSUE THREAD

**Issue by kennethlarsen** [inkle/inky#20]
I get the following error when typing 'npm start' on linux (currently trying to make a build for linux)

`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at Object.<anonymous> (/home/kenneth/dev/inky/Inky-linux-x64/resources/app.asar/main-process/inklecate.js:19:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/kenneth/dev/inky/Inky-linux-x64/resources/app.asar/main-process/projectWindow.js:6:19)`

**Comment by joethephish** [comment]
Hmm. Did you run `npm install` first from the `app` directory?

Otherwise, I'm not sure I'm afraid! Would you be able to try debugging it? We don't have a Linux setup here.

**Comment by kennethlarsen** [comment]
@joethephish I did, yes. I'm debugging at the moment. Will report if I find a solution. 

What version of node do you use?

**Comment by joethephish** [comment]
I'm currently on `v5.2.0`.

**Comment by kennethlarsen** [comment]
@joethephish I finally found a fix for this. The error was caused by the lack of linux in inklecateNames in inklecate.js and the weird stuff in line 35 which had to be changed to linux. 

This is how it looks now on Linux. Will debug further (but let me know if the bug is known to you)

![inkle](https://cloud.githubusercontent.com/assets/1408595/16521575/1b37c8f2-3f98-11e6-8996-6126e0c1032a.png)

**Comment by joethephish** [comment]
Ah, great, well found @kennethlarsen!

To give you a bit more background on inklecate:

* The Windows version relies on .NET being installed (hence it's a few 100k). You can pretty much rely on Windows having this installed (and I believe if it's not, Windows knows how to tell users what to do)
* The Mac version is natively compiled and statically linked with the Mono runtime (hence it being multiple MB)
* On Linux I'm not sure of the right solution. I haven't investigated whether you can do the same as on Mac and natively compile/link it with Mono. And I don't really know the ecosystem - are Linux users expected to be more technical, and therefore happy to simply be told to install Mono? Since if that's the case, you can simply re-use the Windows build, and instead of calling inklecate directly, you'd need to run `mono inklecate_win.exe`.

If you're still having problems beyond that last point, I'd recommend you try running inklecate directly just to make sure you can get it to run correctly outside of inky, as a starting point.

**Comment by joethephish** [comment]
Ah, and in terms of the window layout, you might want to take a look at all mentions of `.win32` in `main.css`, and add `.linux` versions too. So, for example:

```
.win32 #toolbar {
  height: 30px;
  background: #f0f0f0;
}
```

Would become:

```
.win32 #toolbar, .linux #toolbar {
  height: 30px;
  background: #f0f0f0;
}
```

...that should fix things like the doubled up window title.

**Comment by kennethlarsen** [comment]
@joethephish I think the best solution is to use Wine which many Linux users already use. And it's not too much to ask to install it (and then Inky more or less works out of the box). 

This is a screenshot my current Linux build:
![inkylinux](https://cloud.githubusercontent.com/assets/1408595/16534359/7514e12e-3fdf-11e6-8cad-9a5d4d2dbab6.png)

So far it works with no errors. It feels a bit slow on updating the preview part when changing the code. I will try to compare with the OSX build. 

I'll do some more testing, look at the cosmetics and finally do a PR ;)
