### ISSUE TITLE
Diverts referring to other files load as errors

### ISSUE THREAD

**Issue by lunarcloud** [inkle/inky#238]
When first loading up, they show as errors.
If you make any edit, it causes it to reevaluate and they're no longer errors.

Before:
![image](https://user-images.githubusercontent.com/1565970/78462447-05a89280-76a0-11ea-8130-bdef1cd23e47.png)
After:
![image](https://user-images.githubusercontent.com/1565970/78462483-7b146300-76a0-11ea-924b-67ffc4f66e88.png)

**Comment by joethephish** [comment]
Hmm, this is because the compiler begins before it realises that the file watcher is going to find more (required!) files in the project. This probably needs a bit of investigation - perhaps there's a way to make the file watcher run synchronously on first run, or somehow get a callback when it's finished doing a full first scan, and wait for that before doing a first compile.

**Comment by joethephish** [comment]
Ahha! Looking at the docs for [chokidar](https://github.com/paulmillr/chokidar), it seems this is what we want:

    .on('ready', () => log('Initial scan complete. Ready for changes'))

**Comment by joethephish** [comment]
Fixed in 0171cbfa5b9f1112733ef453f561c1e83d59525f. This one makes me happy, it was bugging me for a while (every time we opened up the Heaven's Vault project in inky it would always start by spewing looooads of errors before recompiling and being fine... now it works great)
