### ISSUE TITLE
Any way to get the compiler errors/warnings in other editors?

### ISSUE THREAD

**Issue by klootas** [inkle/inky#252]
Hi there!
Loving ink and inky but would love to be able to use the editors I'm more used to (preferably Visual Studio or Visual Studio Code). I managed to install the textmate bundles in VS and the ink package in VS Code, so I got color coding working in both editors. But I would LOVE to get the compiler errors and warnings in inky to work too... I figure this should be doable at least in VS Code, right?

Also, I messed around with the support for Sublime Text 3 but could only get color coding to work there as well (I'm on Windows, perhaps that works better on Mac).

Thanks!

**Comment by joethephish** [comment]
The way to do this in VSCode is to write an extension with full ink compiler integration.

To be honest, if VSCode had existed before I started work on Inky, this probably would've been my preferred approach, since you would have all the benefits of Inky alongside having a fully featured mature editor.

However, writing a full VSCode extension is no small undertaking I'm afraid. The recommended way of doing this is to make a [Language Server](https://langserver.org), but that's very non-trivial I'm afraid!
