### ISSUE TITLE
Feature: incorporate documentation

### ISSUE THREAD

**Issue by joningold** [inkle/inky#27]
Just a markdown viewer, if that's easy to do  -but it would mean inky was a one-stop place to learn, write and publish ink.

**Comment by joethephish** [comment]
Great idea!

I was also thinking it would be good to have something like an "Insert"
menu with a set of snippets for all the types of syntax you can get, both
basics and more complex examples.

**Comment by joningold** [comment]
Inform 7 does that with all of its examples, and it works really nicely.

jon

**Comment by joethephish** [comment]
Added needs-UI-design label, because it would probably be good to have a chapter index, rather than purely replicating the "writing with ink" doc within a separate window (although that would be a good start).

**Comment by joethephish** [comment]
For anyone who wants to have a go at this one, it's relatively straightforward, and wouldn't require much knowledge of the inky codebase, though it requires learning a bit about the basics of [Electron](http://electron.atom.io/).

* Start by adding a menu to [appmenus.js](https://github.com/inkle/inky/blob/master/app/main-process/appmenus.js) to show the ink documentation. Have it trigger a callback in [main.js](https://github.com/inkle/inky/blob/master/app/main-process/main.js) like the others (e.g. `exportJson`).
* Instead of making a call to the `ProjectWindow` like the others, instead create a new BrowserWindow with a new documentation viewer HTML file, according to the [Electron docs](http://electron.atom.io/docs/api/browser-window/). Also see the [Electron QuickStart](http://electron.atom.io/docs/tutorial/quick-start/) docs on how their overall model works.

**Comment by joethephish** [comment]
For the Insert Snippet feature I mentioned, it starts similarly to the documentation viewer, and then diverges a bit:

* Start by adding menus to [appmenus.js](https://github.com/inkle/inky/blob/master/app/main-process/appmenus.js). Given we'll want a large number of snippets, you might want to set it up in a separate file.
* There's then a slight tedious but straightforward chain of data passing / adding hooks you'll have to do to trigger the insertion of the snippet: In the main process: `appmenus.js` -> `main.js` -> `projectWindow.js`, then via IPC into the renderer -> `inkProject.js` (activeInkFile) -> `inkFile.js` and insert some text by accessing the `aceSession`.

**Comment by Julisep** [comment]
I could try to implement the documentation.

**Comment by joethephish** [comment]
Great! Let me know if you need any help...

**Comment by joethephish** [comment]
Documentation now in [latest build](https://github.com/inkle/inky/releases/tag/0.4.0). Thanks @Julisep!

**Comment by And0k** [comment]
not useful: the searching is not possible
