### ISSUE TITLE
Gathers auto-completing when they shouldn't be

### ISSUE THREAD

**Issue by Mixwhelan** [inkle/inky#29]
When you have a few bits of nesting in your code, inky starts to autocomplete your gathers to whichever one you've been using the most. It also recognises TAB as accepting the auto-complete so indenting after a gather point will automatically create a nested gather when you don't want it to.

**Comment by joethephish** [comment]
Right now we're entirely relying on [Ace]'s built-in auto completer, which includes all "words" in their snippet dictionary. Unfortunately their definition of a word also includes punctuation! In order to fix this, I believe we'd have to re-implement a new completer.

It's unlikely to be a priority for me right now, but if anyone with JavaScript experience wants to have a go at it, it may be relatively straightforward, and require no pre-existing knowledge of the inky codebase:

* Start by opening [editorView.js](https://github.com/inkle/inky/blob/master/app/renderer/editorView.js). Switch off [enableLiveAutocompletion](https://github.com/inkle/inky/blob/master/app/renderer/editorView.js#L22).
* Take a look at the [commented out completer starting on line 30](https://github.com/inkle/inky/blob/master/app/renderer/editorView.js#L30) for how to add a different completer to the editor.
* Although Ace [has documentation](https://ace.c9.io/#nav=api), I don't think they have any for completers. But their source code is fairly readable, so you might want to see how the implemented [their own auto completer](https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete/text_completer.js). You could start by copy/pasting their definition of the auto completer in, and start hacking it (e.g. by modifying their regex which splits up the document into words).

**Comment by joethephish** [comment]
Related: by adding a custom completer, #21 (adding global variables to completion options) would also become possible.
