### ISSUE TITLE
Export not working linux 64

### ISSUE THREAD

**Issue by boban-dj** [inkle/inky#339]
Inky version 4.2.12
Distro: Linux archZ840 5.10.28-1-lts

Downloaded Inky from here :[https://github.com/inkle/inky/releases/download/0.12.0/Inky_linux.zip](url)

    Run ./Inky
    save project > File > Export for Web

Error

    Could not export: Unexpected error

I see no other error messages in terminal or anywhere else, only:

    Launching inklecate for session id 'inky2_ink_44WzS80_3'
    - Ended inklecate session id inky2_ink_44WzS80_3

Otherwise the editor is working fine and I can follow the tutorials from here [https://www.inklestudios.com/ink/web-tutorial/](url)
Already tried to give all write+exec permissions to Inky install folder

**Comment by johnstyle** [comment]
I have the same error when I want "Export for web" or "Export story.js only".

In the developer tools, there is this error log :

```
/opt/Inky/resources/app.asar/renderer/liveCompiler.js:144 Uncaught TypeError: callback is not a function
    at completeExport (/opt/Inky/resources/app.asar/renderer/liveCompiler.js:144)
    at EventEmitter.ipc.on (/opt/Inky/resources/app.asar/renderer/liveCompiler.js:328)
    at EventEmitter.emit (events.js:182)
completeExport @ /opt/Inky/resources/app.asar/renderer/liveCompiler.js:144
ipc.on @ /opt/Inky/resources/app.asar/renderer/liveCompiler.js:328
emit @ events.js:182
```

**Comment by scotus-49** [comment]
I had the same problem and error messages with Ubuntu 21.04.  I have had similar problems with earlier binary releases for linux - they did not work on Ubuntu. 

What I did - I installed mono and the various dependencies, then downloaded and built inky from the latest release source-code. From the unpacked **inky-0.12.0** directory I simply ran the  ./ INSTALL_AND_RUN.command, and install went without a problem. Inky started, and on loading a test file, I was able to export to web, and the resultant files opened in Firefox. Make sure that the "export-for-web-template" has been installed in the app folder.

Installing the mono files was not without a few problems, since the latest Ubuntu version is no newer than for 20.04, but it was possible.

Hope this helps.

**Comment by nitnelave** [comment]
Hey @scotus-49, I tried doing the same thing as you did. Indeed, from cloning the repository there's a problem with the electron installation.
But when I did it from the source zip, when I tried to export for web (or to anything, for that matter), I got the "Could not export: Unexpected error" again.

And if I try to open a file (instead of creating a new one), it gets stuck trying to load it (the story doesn't appear, the loading widget keeps spinning in the top right, and export doesn't work because it's not loaded). And that's with a one-line story :)

**Comment by scotus-49** [comment]
I downloaded the tar.gz 0.12.0 [source code file](https://github.com/inkle/inky/archive/refs/tags/0.12.0.tar.gz), unpacked it, cd'd into the directory and went from there.

My main problem had been that a recent Ubuntu upgrade had removed my mono installation, and reinstalling that took forever, with about  400MB of files involved. 

NOTE: I've just done a fresh build to recheck, and I get " > inky@**0.11.0 postinstall**
" and "> inky@**0.11.0 start**" coming up in the command line, and in Inky: **About** I have Inky version 4.2.12, Ink version 0.9.0, inkjs version 1.10.2

I understood that this Inky was having Ink 1.0, but that does not seem to be the case when it's built from the source code. I'm starting to get a bit confused... The package.json file in the app folder also has this Inky as version 0.11.0. I'll open a new issue over this.

**Comment by boban-dj** [comment]
Thanks @scotus-49, on Archlinux installed missing dependancy mono with `pacman -S mono`
now export is working as expected. I just used the Linux package from Inky website [https://github.com/inkle/inky/releases/download/0.12.0/Inky_linux.zip](url)
