### ISSUE TITLE
Bug: Cmd+R silently loses unsaved work

### ISSUE THREAD

**Issue by joningold** [inkle/inky#49]
the Cmd+R shortcut reloads rather aggressively; if you have unsaved work it reloads without prompting, losing everything since last save. :(

**Comment by joethephish** [comment]
Yeeeah that's really a debug left-in-by-default thing because the app is built using web tech... really the option ought to be taken out of release builds, or at least only turned off if the user switches on a special developer/debug mode.

But yeah, you're right, we could probably go through the usual "are you sure" flow first, either way.

**Comment by joningold** [comment]
I've done it twice now trying to find/replace :(

Jon

**Comment by joethephish** [comment]
Sorry :-(

**Comment by joethephish** [comment]
Okay, added an "are you sure?" in 51b88de195824670f759f83084891ab63ca9f21e
