### ISSUE TITLE
Selecting Help -> Learn More - error

### ISSUE THREAD

**Issue by dmccan** [inkle/inky#69]
Running Inky 64-bit Windows v1.4.3 - Clicking on the Help, Learn More menu item the first time does nothing and the second time gives a JS error: 

`Uncaught Exception: ReferenceError: inklecate is not defined`

**Comment by mehalon** [comment]
Any update on this one?

**Comment by gw1108** [comment]
Looking at the source code there is appmenu.js at line 200 it says:
inkelcate("hello world").

I think it's safe to say that Learn More menu item was a test menu item and is not actually supposed to be in the final product. I'm not sure what it's supposed to do at all so I suggest we remove the menu item entirely since "Show Documentation" already works.

**Comment by joethephish** [comment]
Yup! Pull request away if you'd like.

**Comment by triptych** [comment]
This bug is still here after 3 years. It's a simple fix... Why was the PR closed but not merged? https://github.com/inkle/inky/blob/dc8a466d0d6304d67337bad24fc7b44d1eebd7d1/app/main-process/appmenus.js#L222

**Comment by joethephish** [comment]
🤷‍♂️ whatever, trivial fix, done in c8014f9f57e45685b1854fe953af291329a97ff4!

**Comment by triptych** [comment]
Thank you sir! Hope I didn't sound ungrateful. I really dig Ink and want to invest in making IF with it. Perhaps next time instead of just kvetching I'll send a PR :)

**Comment by joethephish** [comment]
No worries! I find it hard to stay on top of PRs and ink-related todos but thought i may as well just nip this one straight in the bud :)

**Comment by lunarcloud** [comment]
Since this is fixed, let's close the issue.
