### ISSUE TITLE
Determining Inky Version

### ISSUE THREAD

**Issue by lhughes41** [inkle/inky#86]
How can I tell please? For an installed version.  I check the "help" menu for example but couldn't spot.
 Thank you,
   Luke

**Comment by joethephish** [comment]
This is how you do it on Mac... not sure about Windows/Linux - can anyone verify?

![image](https://cloud.githubusercontent.com/assets/858967/23096684/6fe2d1d4-f619-11e6-8718-4d89b9b2f175.png)

![image](https://cloud.githubusercontent.com/assets/858967/23096686/78e75cc8-f619-11e6-9d00-c89b95aeb78e.png)

Note that the version number hasn't been entirely robust until recently because the frameworks we use (Electron and Electron Packager) weren't great at propagating the version number into the right places until recently.

**Comment by Julisep** [comment]
On Windows it works the same.

**Comment by rubereaglenest** [comment]
On Windows, the Learn More option, produces a Javascript error.

![inky_error 2017-03-23 10 59 05](https://cloud.githubusercontent.com/assets/17875543/24242479/230561a2-0fb8-11e7-8bb1-7e69618ff5fa.png)

**Comment by lunarcloud** [comment]
Was able to confirm via "Help > About"
![image](https://user-images.githubusercontent.com/1565970/149160794-434664c3-ca32-4ac9-825a-8140b45737f7.png)

I think we can close this @lhughes41 yeah?

**Comment by lhughes41** [comment]
Thanks everyone, and for the prompt @lunarcloud  
Closing,
