### ISSUE TITLE
Feature: buglist sorting

### ISSUE THREAD

**Issue by joningold** [inkle/inky#93]
When you make a fundamental error (eg. a missing } on a condition) in an include file it tends to generate a large number of errors (because the file fails, and so references to inside it fail). 

But in the list there's a clear hierarchy of bugs, with things like  "Unresolved variable" and "Missing divert target" being secondary, and "Expected closing }" - or whatever - being primary. 

It'd be useful if bug reports in inky were sorted by this kind of priority, so you can quickly find and fix the "important" error. (Currently I tend to scroll through the list to spot it by eye.)

Note this wouldn't even need to be bullet-proof to be helpful! And if you felt sorting was too strong, maybe bold-typing..?

**Comment by joningold** [comment]
Alternatively, prevent errors from causing cascades like this. Current types that fail:

Missing } bracket 
<img width="561" alt="screen shot 2017-10-11 at 12 20 22" src="https://user-images.githubusercontent.com/930979/31437994-369c717c-ae7f-11e7-88c6-d19597cb7371.png">

Missing ] bracket on a choice
<img width="518" alt="screen shot 2017-10-11 at 12 22 36" src="https://user-images.githubusercontent.com/930979/31438002-3d312a46-ae7f-11e7-8e69-c5ada8a3bcc0.png">

Missing > on a divert after a tunnel 
<img width="315" alt="screen shot 2017-10-11 at 12 24 06" src="https://user-images.githubusercontent.com/930979/31438011-45f12686-ae7f-11e7-86a9-82c7b261575e.png">

**Comment by joethephish** [comment]
Turns out this boils down to bad behaviour on the compiler's part, in that if there were any errors at all in an include, it would ditch it entirely, rather than attempting to continue with what it had. This caused everything that was defined in that include to go missing, causing zillions of errors instead of just one small one. Fixed in the ink repo in this commit: https://github.com/inkle/ink/commit/725bbbd2f44819658ea5aff6c21911dd7cf84822, so it'll make it into the next ink + inky releases.
